#!/bin/bash
#ddev-generated

## Description: Open an interactive Cypress window
##              https://docs.cypress.io/guides/guides/command-line#cypress-open
## Usage: cypress-open [arguments]
## Example: "ddev cypress-open --config cypress.json"
## On Mac you may need to pass the baseUrl here
## CYPRESS_baseUrl=https://test.ddev.site cypress open --project . "$@"

cypress open --project . "$@"
