#!/bin/bash
#ddev-generated
## Description: Use Cypress in "runner" mode.
##
## Usage: cypress-run [arguments]
## Example: "ddev cypress-run --browser chrome"
## On Mac you may need to pass the baseUrl here
## CYPRESS_baseUrl=https://test.ddev.site cypress run "$@"

cypress run "$@"
