#!/bin/bash
#ddev-generated
## Description: Commands for managing the global Cypress cache.
## https://docs.cypress.io/guides/guides/command-line#cypress-cache-command
## Usage: cypress-cache [arguments]
## [path], [list, --size], [clear], and [prune]
## Example: "ddev cypress-cache list"

cypress cache "$@"
